### PR TITLE
closes #47

### LINKED ISSUE #47: Reducing amount of warnings
Looking at the code in WebStorm is kind of ridiculous in regards to the amount of warnings. At least changing from `var` to `let` would already be a huge improvements. And since the minimum requirement for NodeBB is now NodeJS 6 this shouldn't be a problem.

### PR DESCRIPTION
**Pull request by julianlam**
... eslinting

### CODE REVIEW

**Comment by julianlam** [comment]
This was done blind, so you actually have to check that functionality still works :smile:

**Comment by Dravere** [comment]
Working on fixing the merge and some additional warnings. Also testing it :)

**Comment by Dravere** [comment]
@julianlam Ok, fixed it and made some additional changes. Only one question: Are you using Yarn? Since I see a yarn.lock in there. Should I switch to Yarn? I'm currently using NPM and was thinking to actually push the `package-lock.json` next. But this might be redundant.

**Comment by Dravere** [comment]
Also just checked something. This will have to wait for release 6.0.0 of this plugin. Since the current compatibility is set to NodeBB 1.5.0. NodeBB 1.5 still had support for NodeJS 4.x. And NodeJS 4.x had no good support for const. Only with NodeBB 1.7.0 NodeJS was upped to 6.x which had good const support.

With the release of 6.0.0 of this plugin I will up the compatibility to NodeBB 1.10 anyway.

**Comment by julianlam** [comment]
`yarn.lock` and `package-lock.json` can co-exist peacefully, however, neither are required and so you could actually safely remove them too. In fact I've had nothing but problems with `package-lock.json`, but to each their own.

Also yeah, next version of Solr should just drop compatibility for anything but latest v1.10.x

**Comment by Dravere** [comment]
They can co-exist but it kind of doesn't make any sense having both, since it would undermine what they try to achieve. Those lock files are there to be able to recreate the exact same package configuration on another machine and thus have clean reproducible results. If you leave both in and as far as I know they don't synchronize then you basically lose that feature again.

May I ask what problems you had with `package-lock.json` compared to `yarn.lock`? I've never really saw the need for yarn anymore after NPM finally got their stuff together and provided the additional features that yarn introduced to the ecosystem.

**Comment by julianlam** [comment]
Oh it's very much political as opposed to technical... but also I've had cases where an npm install got completely fubared and nothing would install properly until `package-lock.json` was deleted.

You shouldn't be using both npm and yarn, so they wouldn't conflict, but the file that remains (if one remains) should be the one that the maintainers agree to use :smile:

**Comment by Dravere** [comment]
I honestly don't have a very strong opinion on this. Thus I don't mind trying out Yarn with this project. We can always switch back to NPM if this was a bad decision :wink:

**Pull request merged**
