### PR TITLE
Batch collecting topic meta data instead of in one big go

### PR DESCRIPTION
**Pull request by Dravere**
I ran into issues when there are a lot of topics and limited memory. It resulted in the MongoDB query running for very long times and thus timing out. Batching it makes it run without any problems.

Review as necessary. I tested it on a forum with >2 mio posts and >200,000 topics.

### CODE REVIEW

**Comment by Dravere** [comment]
@julianlam Made the requested changes. Sorry that it took me so long.

Btw. I'll probably have additional pull requests. As you can see on the readme of my fork (branch cppnet) I still have changes from the main plugin. And I would like to provide these to this plugin. Also with the recent change of the search hook it would be nice to update this plugin to make use of the additional data provided via the hook. But that also probably means that an index rebuild is mandatory for it, since for example timestamps should be included in the index.

**Comment by julianlam** [comment]
Any way you could make those changes backwards compatible and not require a re-index?

**Comment by Dravere** [comment]
Only to make it clear the re-index hasn't anything to do with this pull-request. This was just a tangent on future changes I would like to provide. I'm opening a separate issue so this can be discussed there.

**Comment by julianlam** [comment]
Awesome! Let me know if you'd like me to publish a new version immediately, or if I should wait for your subsequent PRs

**Comment by Dravere** [comment]
I'd recommend waiting. There is still pull-request #40 and I'll provide three additional pull-request soon (fixing a possible error, removing some unused parts and improvements of the progress report).

**Comment by julianlam** [comment]
Could even make you maintainer 😁

**Comment by Dravere** [comment]
I have no clue what this would mean. But for now I'm using Solr for the search in NodeBB and I'm very happy with it. Thus helping maintaining it is an obvious step.

**Comment by julianlam** [comment]
Ah, that'd mean giving you full access to this repo and the corresponding
npm package

**Comment by Dravere** [comment]
That would be up to you. But I have to say I don't mind someone reviewing my pull-requests. It is usually always a good idea to do this as it has been shown over and over again that it improves code quality.

But if you'd like to rather invest your time into other parts of the NodeBB project and feel comfortable to let me lose on this project, it is up to you :smiley:

**Comment by julianlam** [comment]
Done :+1: (actually, as it turns out, you already _are_ maintainer for this GitHub repo). You now have push access to the npm package.

**Pull request merged**
